### ISSUE TITLE
I can't seem to use ES6 modules

### ISSUE THREAD

**Issue by andrerpena** [reactjs/express-react-views#26]
I'm considering using `express-react-views`, however, I've run into a problem with the simplest examples while using ES6. 

Here's how my View look like:

```js
import React from 'react';
import DefaultLayout from './layouts/default';

var HelloMessage = React.createClass({
    render: function() {
        return (
            <DefaultLayout title={this.props.title}>
                <div>Hello {this.props.name}</div>
            </DefaultLayout>
        );
    }
});

export default HelloMessage;
```

Error:

```
SyntaxError: Unexpected reserved word
   at exports.runInThisContext (vm.js:73:16)
   at Module._compile (module.js:443:25)
   at Object.require.extensions.(anonymous function) [as .jsx] (C:\Projects\Git\gearz-node\node_modules\express-react-views\node_modules\node-jsx\index.js:26:12)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at View.renderFile [as engine] (C:\Projects\Git\gearz-node\node_modules\express-react-views\index.js:44:23)
   at View.render (C:\Projects\Git\gearz-node\node_modules\express\lib\view.js:93:8)
   at EventEmitter.app.render (C:\Projects\Git\gearz-node\node_modules\express\lib\application.js:566:10)
```

Is there anything I can do to make it work? Using `babel` or something?

Thanks very much.

**Comment by zpao** [comment]
jstransform (which is ultimately what we use to transform through a couple dependencies) doesn't transform `import` or `export` so that won't work just yet. Right now using node-jsx is pretty hard-coded in there. But it might be a good idea to make that opt in. Or just switch to babel...

**Comment by andrerpena** [comment]
Thank you very much
Em 14/04/2015 21:11, "Paul O’Shannessy" <notifications@github.com> escreveu:

**Comment by xpepermint** [comment]
+1 for babel

**Comment by zpao** [comment]
We switched to babel in v0.8 (see #29). This should be working for you now (unless you're using Windows in which case see #33). So I'm going to close out, but let me know if there are still issues.
