### ISSUE TITLE
Error with babel when using babel/register

### ISSUE THREAD

**Issue by ahayschi** [reactjs/express-react-views#46]
I'm encountering the following error in a small project I'm working on: 

```
Error: only one instance of babel/polyfill is allowed
   at Object.<anonymous> (/Users/Alex/code/projects/marketplace/node_modules/express-react-views/node_modules/babel/node_modules/babel-core/lib/babel/polyfill.js:16:9)
   at Module._compile (module.js:460:26)
   at Module._extensions..js (module.js:478:10)
   at Object.require.extensions.(anonymous function) [as .js] (/Users/Alex/code/projects/marketplace/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:215:7)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (/Users/Alex/code/projects/marketplace/node_modules/express-react-views/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node-polyfill.js:11:1)
   at Module._compile (module.js:460:26)
   at Module._extensions..js (module.js:478:10)
   at Object.require.extensions.(anonymous function) [as .js] (/Users/Alex/code/projects/marketplace/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:215:7)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
```
The entry file for the server has ```require('babel/register');``` in order to use ES6 style imports, etc. throughout the rest of the project. But it seems like there's a conflict between this package's babel and the project's. Any idea why there's a conflict, or is this totally on my end?

**Comment by zpao** [comment]
This is pretty much the same as #40. The problem isn't on your end, just that we're also using `babel/register`. We're going to need a way to disable that behavior.
