### ISSUE TITLE
TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by 109km** [reactjs/express-react-views#62]
In the `index.jsx` file , if I don't use `this.props`, it will be OK:
```jsx
const React = require('react');

let App = React.createClass({
    render: () => {
        return (

            <div>
                Hello,this is jsx!
            </div>
        );
    }
});

module.exports = App;
```
Here is the renderd html :
```html
<!DOCTYPE html><div>Hello,this is jsx!</div>
```

If I want to use `this.props`, it will throw an error, and here is my code below:
```jsx
const React = require('react');

let App = React.createClass({
    render: () => {
        return (

            <div>
                Hello,this is jsx!{this.props.name}
            </div>
        );
    }
});

module.exports = App;
```
In `server.js` , the code is like this:
```javascript
app.get('/',(req,res)=>{

    res.render('index', { name: 'John' });

});
```

The error log:
```
TypeError: Cannot read property 'props' of undefined
    at [object Object].render (/Users/xinhengs/Desktop/QunarDevs/qact/webapps/views/index.jsx:8:36)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactPerf.js:66:21)
    at /Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactServerRendering.js:70:32
    at ReactServerRenderingTransaction.Mixin.perform (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/Transaction.js:136:20)
    at Object.renderToStaticMarkup (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/react/lib/ReactServerRendering.js:68:24)
    at View.renderFile [as engine] (/Users/xinhengs/Desktop/QunarDevs/qact/server/node_modules/express-react-views/index.js:46:32)
```
Does anyone knows why ?

**Comment by Chunlin-Li** [comment]
I have same problem to you,  use function() {} instead of  () => {} will work.  
maybe it not support all es6 feature which node js implemented.

**Comment by 109km** [comment]
@Chunlin-Li Thank you so much!! The problem just freaks me out.

**Comment by lijunle** [comment]
Use this syntax:

```js
let App = React.createClass({
    render() {
        return (
            <div>
                Hello,this is jsx!
            </div>
        );
    }
});
```

Arrow function in ES6 **does** not capture `this` keyword. See [this](https://babeljs.io/docs/learn-es2015/). Your error is expected.

**Comment by Chunlin-Li** [comment]
@lijunle very helpful! Thanks!

**Comment by 109km** [comment]
@lijunle Thanks very much!

**Comment by 109km** [comment]
@lijunle what is this syntax ? I can't find any docs about it. 

`()` comes first , then `{}` 

```
render() {
        return (
            <div>
                Hello,this is jsx!
            </div>
        );
    }

```

**Comment by Chunlin-Li** [comment]
@109km I know `{foo, bar}` is the syntax sugar of `{foo: foo, bar: bar}` in ES6.  I guess `{render() {...}}` is the same, maybe it means `{render : function render() {...}}`. 
You can test that in node REPL

**Comment by 109km** [comment]
@Chunlin-Li Thanks very much, I'll try.
