### ISSUE TITLE
Render es2015 jsx in server side error

### ISSUE THREAD

**Issue by darkautism** [reactjs/express-react-views#65]
The log object is undefined.
My Log:
```
error:  TypeError: Cannot call method 'error' of undefined
    at OptionManager.mergeOptions (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .jsx] (/home/kautism/workspace/mail/node_modules/express-react-views/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at View.renderFile [as engine] (/home/kautism/workspace/mail/node_modules/express-react-views/index.js:43:23)
    at View.render (/home/kautism/workspace/mail/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/kautism/workspace/mail/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/home/kautism/workspace/mail/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/kautism/workspace/mail/node_modules/express/lib/response.js:961:7)
```

This jsx can be compile by my client side compiler
jsx:
```javascript
'use strict'
import React from 'react';
import {render} from 'react-dom';
import DefaultLayout from './layouts/DefaultLayout.jsx';
import CommandBar from './Component/CommandBar.jsx';
import LogList from './Component/LogList.jsx';
import PageController from './Component/PageController.jsx';
if (/*global*/typeof window !== 'undefined') {
	require('jquery');
	require('bootstrap');
}

class LoglistPage extends  React.Component {
	static defaultProps(){
        return {
            title: 'NoTitle'
        };
    }
    
	render(){
		return (
			<DefaultLayout>
			    <h1>AutoTest List</h1>
			    <hr />
			    <CommandBar></CommandBar>
			    <LogList></LogList>
			    <PageController></PageController>
			</DefaultLayout>
		);
	}
};

export default LoglistPage;
```

My .babelrc
```json
{
  "presets" : ["react", "es2015"]
}
```

**Comment by lijunle** [comment]
This project has not used babel@6 yet. If you are using this package and babel@6 with npm@3. It gets a chance to mess up everything. Please try to use my fork in your `package.json`:

```json
{
  "dependencies": {
      "express-react-views": "lijunle/express-react-views#babel-6"
  }
}
```

**Comment by julientypeform** [comment]
I have had a similar issue:

```
TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (project/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (project/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (project/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
There was nothing particular in my code, and I made sure to clear any ES6 syntax, to no avail. Even the example was failing.
Pointing to the fork solved it, but maybe the main repo should be updated?
Thanks

**Comment by lijunle** [comment]
@zpao has taken care of this. See https://github.com/reactjs/express-react-views/pull/58.
