### ISSUE TITLE
Using with react-bootstrap package

### ISSUE THREAD

**Issue by isko-algorithm** [reactjs/express-react-views#86]
I am using this package to replace KeystoneJs's views from jade to jsx. All seems fine until I tried using the package ```react-bootstrap``` (http://react-bootstrap.github.io) in order to further simplify my UI requirements. However, upon trying this out, an error appeared and below is the error message:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Error thrown for request: /
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/fbjs/lib/invariant.js:38:15)
    at instantiateReactComponent (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/react/lib/instantiateReactComponent.js:85:134)
    at /home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/react/lib/ReactServerRendering.js:42:31
    at ReactServerRenderingTransaction.Mixin.perform (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/react/lib/Transaction.js:136:20)
    at renderToStringImpl (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/react/lib/ReactServerRendering.js:38:24)
    at Object.renderToStaticMarkup (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/react/lib/ReactServerRendering.js:78:10)
    at View.renderFile [as engine] (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/express-react-views/index.js:54:32)
    at View.render (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/express/lib/response.js:960:7)
    at View.<anonymous> (/home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/keystone/lib/view.js:337:13)
    at /home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/keystone/lib/view.js:372:3
    at /home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/async/lib/async.js:52:16
    at /home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/async/lib/async.js:269:32
    at /home/gabrielgagno/Documents/projects/experiments/com-keystone/node_modules/async/lib/async.js:44:16

```

I would just like to know if there is some sort of incompatibility between these packages, and if there's none, I want to know how to make them work together. Thanks!

**Comment by zpao** [comment]
I don't think there's any incompatability. As long as you can ReactDOMServer.renderToStaticMarkup then it should be fine. This error stack isn't super useful but the invariant you're hitting indicates that perhaps an import or require isn't correct and you aren't getting a React component but some other object, and then trying to render it.

**Comment by isko-algorithm** [comment]
Am I doing this right?

```javascript
var React = require('react');
var ReactDOMServer = require('react-dom/server');
var {Button} = require('react-bootstrap');
const buttonInstance = (
	<Button>
		Click
	</Button>
);

ReactDOMServer.renderToStaticMarkup(buttonInstance);
```

I am still receiving an error same as the one above.

**Comment by zpao** [comment]
You shouldn't have to do any rendering yourself using this express renderer, it handles that for you. If I run your code on its own and console.log it works.

```js
var React = require('react');
var ReactDOMServer = require('react-dom/server');
var ReactBootstrap = require('react-bootstrap');
var Button = ReactBootstrap.Button;
var buttonInstance =
  React.createElement(Button, null, 'Click')

console.log(ReactDOMServer.renderToStaticMarkup(buttonInstance))

// Outputs:
// <button type="button" class="btn btn-default">Click</button>
```

**Comment by isko-algorithm** [comment]
Thanks. I think I got the idea already.
