### ISSUE TITLE
Get an error: Unexpected token import

### ISSUE THREAD

**Issue by LzxHahaha** [reactjs/express-react-views#99]
I got an error message:

```
D:\Works\Code\JS\plusone\src\views\components\Page.js:5
import React from 'react';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Works\Code\JS\plusone\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object. (D:/Works/Code/JS/plusone/src/views/pages/User.js:8:1)
```

I try use `createEngine` like this:

```
// this is copy from .babelrc
app.engine('js', ReactViews.createEngine({
  babel: {
    "presets": ["es2015", "stage-3", "react"],
    "plugins": [
      "transform-class-properties",
      "transform-object-rest-spread"
    ]
  }
}));
```

but did not work,  I must use babel to translate it by myself, how to fixed it?

**Comment by Stevearzh** [comment]
I met the same problem when I import a class (function, const, etc.) from a file outside of the view folder.

**Comment by ssilve1989** [comment]
Bump. How to resolve this?

**Comment by LzxHahaha** [comment]
Add this line:
```
const viewPath = __dirname + (process.env.NODE_ENV === "development" ? '/views/dev/pages' : '/views/pages');
```

and use babel to translate the view's code to `dev` folder:
```
SET NODE_ENV=development&&babel -d ./src/views/dev/ ./src/views/&&babel-node ./src/index
```

**Comment by vkosovskikh** [comment]
Same, why babel preset es2015 still not allowing imports?

**Comment by LzxHahaha** [comment]
@vkosovskikh this module noly support ES5, so you need to compile it first
